---
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcId:
    Type: String
    Description: The VPC this security group resides in

Resources:
  InstanceSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub '${AWS::StackName} Web Security Group'
      GroupDescription: !Sub '${AWS::StackName} Web Security Group'
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceSg:
    Description: Instance security group
    Value: !Ref InstanceSg
